### ISSUE TITLE
Question in useScreenClass Hook

### ISSUE THREAD

**Issue by yaldram** [sealninja/react-grid-system#141] opened 2020-04-25 09:23 UTC
This is a question. ```useScreenClass``` hook is rendering twice and the hook is running twice on each breakpoint. The console.logs are printing twice. I tried debouncing the hook but got the same result. I don't know why but the hook is running twice on each breakpoint. Please let me know why.

```javascript
const ScreenClassProvider = ({
  useOwnWidth,
  fallbackScreenClass,
  children,
}) => {
  const screenClassRef = React.useRef();
  const screenClass = useScreenClass(screenClassRef, fallbackScreenClass);

  console.log("SCREEN CLASS", screenClass);

  return (
    <ScreenClassContext.Provider value={screenClass}>
      {useOwnWidth ? (
        <div ref={useOwnWidth ? screenClassRef : null}>{children}</div>
      ) : (
        <>{children}</>
      )}
    </ScreenClassContext.Provider>
  );
};
```
```javascript
 export const useScreenClass = (source, fallbackScreenClass) => {
  const getScreenClass = useCallback(() => {
    const { breakpoints, defaultScreenClass } = getConfiguration();
    let newScreenClass = defaultScreenClass;

    const viewport = getViewPort(source);
    if (viewport) {
      newScreenClass = "xs";
      if (breakpoints[0] && viewport >= breakpoints[0]) newScreenClass = "sm";
      if (breakpoints[1] && viewport >= breakpoints[1]) newScreenClass = "md";
      if (breakpoints[2] && viewport >= breakpoints[2]) newScreenClass = "lg";
      if (breakpoints[3] && viewport >= breakpoints[3]) newScreenClass = "xl";
    } else if (fallbackScreenClass) {
      newScreenClass = fallbackScreenClass;
    }

    return newScreenClass;
  }, [source, fallbackScreenClass]);

  const [screenClass, setScreenClass] = useState(getScreenClass());

  console.log("HOOK CALLED");

  useEffect(() => {
    function handleWindowResized() {
      setScreenClass(getScreenClass());
    }

    window.addEventListener("resize", handleWindowResized, false);

    return () => {
      window.removeEventListener("resize", handleWindowResized, false);
    };
  }, [getScreenClass]);

  return screenClass;
};
```

Thanks a lot.

**Comment by gerbenmeyer** [comment] 2020-05-10 09:25
Thanks for pointing this out. This should now be fixed in the latest version (6.4.1).

**Closed by gerbenmeyer** 2020-05-10 09:25 UTC

**Comment by yaldram** [comment] 2020-05-10 15:37
@gerbenmeyer Thanks a lot Sir, If you don't mind, please can you highlight what was causing this issue. I see that you only removed the useCallback hook. Thanks in advance.

**Comment by yaldram** [comment] 2020-05-10 15:42
@gerbenmeyer Also why are you not using useEffect(() => {}, []). Like why not pass the [] as a dependency array.

**Comment by gerbenmeyer** [comment] 2020-05-10 17:22
The issue was caused by a redundant `handleWindowResized();` call (see https://github.com/sealninja/react-grid-system/commit/eac7b25c9a1417c67434b2d44507d2c67e5b8c60#diff-2b4ca49d4bb0a774c4d4c1672d7aa781L46).

The empty dependency array will indeed cause less adding and removing of event listeners, I'll add that.

**Comment by yaldram** [comment] 2020-05-11 06:42
@gerbenmeyer Thanks a lot sir for your explanation.
